# Generated by Django 4.2 on 2023-08-04 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cancha",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=150)),
                ("direccion", models.CharField(max_length=150)),
                ("costo_hora", models.IntegerField()),
                ("hora_apertura", models.TimeField()),
                ("hora_cierre", models.TimeField()),
            ],
            options={
                "verbose_name_plural": "Canchas",
            },
        ),
        migrations.CreateModel(
            name="Tipo_Cancha",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=150)),
            ],
            options={
                "verbose_name_plural": "Tipos de Cancha",
            },
        ),
        migrations.CreateModel(
            name="Usuario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ci_numero", models.IntegerField(default=0)),
                ("nombre", models.CharField(max_length=150)),
                ("email", models.CharField(max_length=100)),
                ("direccion", models.CharField(max_length=100)),
                ("telefono", models.IntegerField(default=0)),
                ("contraseña", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name_plural": "Usuarios",
            },
        ),
        migrations.CreateModel(
            name="Reserva",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateTimeField()),
                ("hora_entrada", models.TimeField()),
                ("hora_salida", models.TimeField()),
                ("monto", models.IntegerField()),
                ("estado", models.CharField(max_length=50)),
                (
                    "id_cancha",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="reserva_cancha.cancha",
                    ),
                ),
                (
                    "id_usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="reserva_cancha.usuario",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Reservas",
            },
        ),
        migrations.AddField(
            model_name="cancha",
            name="id_tipo_cancha",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="reserva_cancha.tipo_cancha",
            ),
        ),
    ]
