# Generated by Django 4.2 on 2023-08-04 20:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reserva_cancha", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reserva",
            name="fecha",
            field=models.DateField(),
        ),
    ]
