# Generated by Django 4.2.3 on 2023-08-04 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserva_cancha', '0002_alter_reserva_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipo_cancha',
            name='capacidad',
            field=models.IntegerField(default=0),
        ),
    ]
