# Generated by Django 4.2.3 on 2023-08-04 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserva_cancha', '0003_tipo_cancha_capacidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='cancha',
            name='localidad',
            field=models.CharField(default='', max_length=100),
        ),
    ]
