# Generated by Django 4.2 on 2023-06-17 01:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Empleado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=150)),
                ("departamento", models.CharField(max_length=100)),
                ("fecha_inicio", models.DateField(auto_now_add=True)),
                ("dias_trabajo", models.CharField(max_length=100)),
                (
                    "turno",
                    models.CharField(
                        choices=[
                            ("opcion1", "Mañana"),
                            ("opcion2", "Tarde"),
                            ("opcion3", "Noche"),
                        ],
                        max_length=50,
                    ),
                ),
                ("hora_entrada", models.TimeField()),
                ("hora_salida", models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name="Jornada",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateTimeField()),
                (
                    "tipo_marcacion",
                    models.CharField(
                        choices=[("opcion1", "Entrada"), ("opcion2", "Salida")],
                        max_length=50,
                    ),
                ),
                (
                    "id_empleado",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="control.empleado",
                    ),
                ),
            ],
        ),
    ]
